name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.4"

      - name: Tidy modules
        run: |
          go mod tidy
          go mod verify

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          install-mode: binary

      - name: Fmt
        run: go fmt ./...

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - uses: dominikh/staticcheck-action@v1.4.0
        with:
          version: "latest"
      # - name: Staticcheck
      #   run: staticcheck ./...

      # - name: GolangCI-Lint
      #   run: golangci-lint run

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.26.4
          go-package: ./...

      # - name: Govulncheck
      #   run: govulncheck ./...
